In [1]:
import numpy as np

def spiral(n):
    matrix = np.zeros((n, n), dtype=int)
    row, col = n // 2, n // 2
    num = 1
    step = 1
    
    matrix[row, col] = num

    while step < n:
        # Move to the right
        for _ in range(step):
            col += 1
            num += 1
            matrix[row, col] = num

        # Move up
        for _ in range(step):
            row -= 1
            num += 1
            matrix[row, col] = num

        # Increase step size
        step += 1

        # Move to the left
        for _ in range(step):
            col -= 1
            num += 1
            matrix[row, col] = num

        # Move down
        for _ in range(step):
            row += 1
            num += 1
            matrix[row, col] = num

        # Increase step size
        step += 1

    # Fill the last row
    for _ in range(step - 1):
        col += 1
        num += 1
        matrix[row, col] = num

    return matrix

# Example usage:
n = 3
spiral_matrix = spiral(n)
print("Spiral for n = ", n,":")
print()
print(spiral_matrix)
print()

n = 5
spiral_matrix = spiral(n)
print("Spiral for n = ", n,":")
print()
print(spiral_matrix)
print()

n = 7
spiral_matrix = spiral(n)
print("Spiral for n = ", n,":")
print()
print(spiral_matrix)
print()

n = 15
spiral_matrix = spiral(n)
print("Spiral for n = ", n,":")
print()
print(spiral_matrix)
print()

Spiral for n =  3 :

[[5 4 3]
 [6 1 2]
 [7 8 9]]

Spiral for n =  5 :

[[17 16 15 14 13]
 [18  5  4  3 12]
 [19  6  1  2 11]
 [20  7  8  9 10]
 [21 22 23 24 25]]

Spiral for n =  7 :

[[37 36 35 34 33 32 31]
 [38 17 16 15 14 13 30]
 [39 18  5  4  3 12 29]
 [40 19  6  1  2 11 28]
 [41 20  7  8  9 10 27]
 [42 21 22 23 24 25 26]
 [43 44 45 46 47 48 49]]

Spiral for n =  15 :

[[197 196 195 194 193 192 191 190 189 188 187 186 185 184 183]
 [198 145 144 143 142 141 140 139 138 137 136 135 134 133 182]
 [199 146 101 100  99  98  97  96  95  94  93  92  91 132 181]
 [200 147 102  65  64  63  62  61  60  59  58  57  90 131 180]
 [201 148 103  66  37  36  35  34  33  32  31  56  89 130 179]
 [202 149 104  67  38  17  16  15  14  13  30  55  88 129 178]
 [203 150 105  68  39  18   5   4   3  12  29  54  87 128 177]
 [204 151 106  69  40  19   6   1   2  11  28  53  86 127 176]
 [205 152 107  70  41  20   7   8   9  10  27  52  85 126 175]
 [206 153 108  71  42  21  22  23  24  25  26  51  84 125