In [92]:
import numpy as np
import random

def matmaker(n):
    return np.zeros((n, n))

def algorithm(array):
    n = array.shape[0]
    
    remaining_coordinates = set((i, j) for i in range(n) for j in range(n))
    for i in range(n):
        for j in range(n):
            if remaining_coordinates:
                coord = random.choice(list(remaining_coordinates))
                array[coord] = 1
                
                if coord[1] < n - 1:
                    new_col = coord[1] + 1 if coord[1] % 2 == 0 else coord[1] - 1
                    if 0 <= new_col < n:
                        array[coord[0], new_col] = 0
                        if (coord[0], new_col) in remaining_coordinates:
                            remaining_coordinates.remove((coord[0], new_col))
                elif coord[1] == n - 1:
                    unused_coords = [(i, j) for (i, j) in remaining_coordinates if j == n - 1 and (i, j) != coord]
                    if unused_coords:
                        right_coord = random.choice(unused_coords)
                        if 0 <= right_coord[0] < n:
                            array[right_coord] = 0
                            if right_coord in remaining_coordinates:
                                remaining_coordinates.remove(right_coord)

                if coord in remaining_coordinates:
                    remaining_coordinates.remove(coord)
            else:
                return array
            
    return array
    
n = 50  # Change this to any integer greater than 4
mat = matmaker(n)
print(algorithm(mat))

print("The determinant is: ",np.linalg.det(mat))

[[1. 0. 1. ... 1. 1. 0.]
 [0. 1. 0. ... 1. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]]
The determinant is:  0.0
